-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE db_ecommerce

USE db_ecommerce

CREATE TABLE Usuarios(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	CPF INT NOT NULL
)

CREATE TABLE Produtos(
	Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Preco FLOAT NOT NULL,
	Quantidade INT NOT NULL,
	Categoria VARCHAR(50) NOT NULL,
	Tipo_Pagamento VARCHAR(50) NOT NULL
)

CREATE TABLE Entrega(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Previsao INT NOT NULL, 
	FK_Usuario INT NULL,
	FK_Produtos INT NULL,
	FOREIGN KEY (FK_Usuario) REFERENCES Usuarios (Id),
	FOREIGN KEY (FK_Produtos) REFERENCES Produtos (Id)
)
